services:
  - type: web
    name: somali-police-system
    runtime: php
    buildCommand: bash render-build.sh
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_KEY
        value: base64:RqoqEdZQ3v/eaD1CAPMTyubeMRdqZp5whcKExdlf45Q=
      - key: APP_DEBUG
        value: false
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
